version: "3.0"

services:
  permon:
    container_name: permon
    image: vnevyhosteny/permon:0.0.1
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    ports:
      - '8100:3838'
